config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root  'users#index'
  resources :users do
    resources :schedules
      match 'schedules', to: 'schedules#edit', via: [:patch]
  
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/schedule.rb
class Schedule < ApplicationRecord

  belongs_to  :user

end

app/models/user.rb
class User < ApplicationRecord
  
  has_many :schedules, dependent: :destroy

  validates :name, :email, :password,  {presence: true, uniqueness: true}
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

def index

end

end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController 

  def index
    @schedules = Schedule.where(schedule_params)
    @schedules.each do |schedule|
      @sch = schedule.user_id
      end
    if @sch.present?
     @user = User.find(@sch)
     else 
      User.all.each do |user|
      @user = User.find(user.id)
      end
    end
  end

  def new
      @schedule = Schedule.new
  end

  def create
    @schedule = Schedule.new(in: params[:sch], user_id: schedule_params[:user_id])
    @schedule.save
    respond_to do |format|
      format.html {redirect_to ("/")}
      format.json
    end
  end

  def edit
    user = User.find(schedule_params[:user_id])
    @schedule = Schedule.find(user.schedules.ids.sort.last)
    @schedule.update(out: params[:sch])
    respond_to do |format|
      format.html {redirect_to ("/")}
      format.json
    end
  end

  def show
    @user = User.find(params[:user_id])
    @schedule = Schedule.find(params[:id])
  end


  def update
    @user = User.find(params[:user_id])
    @schedule = Schedule.find(params[:id])
    @schedule.update!(update_params)
    redirect_to action: 'index'
  end

  def destroy
    schedule = Schedule.find(params[:id])
    schedule.destroy
    redirect_to action: 'index'
  end
  
  private
  def schedule_params
    params.permit(:in, :out, :user_id)
  end

  def update_params
    params.require(:schedule).permit(:in, :out, :user_id)
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all.order("id")
    @sch = []
    @users.each do |user|
      if  user.schedules.ids.last.blank?
      @users = User.all.order("id")
    else
      @schedule = Schedule.find(user.schedules.ids.last)
      @sch.push(@schedule.out)
      end
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(name: user_params[:name], email: user_params[:email], password: user_params[:password])
    @user.save
    redirect_to("/users/index")
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to("/users/show")
  end

  def show
    @users = User.all.order("id") 
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to("/users/show")
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_flash.html.erb
<div class="notifications">
    <% flash.each do |key, value| %>
    </div>
    <%= content_tag(:div, value, class: key) %>
    <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>きんたいあぷり</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
  </head>

  <body>
    <%= yield %>
  </body>
</html>
  

app/views/schedules/index.html.erb
<%= render partial: "users/header" %>

<div class="table__box">

<div class="upper_area">
<p class="employee_name">
<%= @user.name %> さんの勤怠状況
</p>
</div>


<table class="list_table__style">

<th>日付</th>
<th>出勤</th>
<th>退勤</th>
<th class="change">修正</th>
<th class="change">削除</th>

<tr>
<% @schedules.each do |schedule| %>
<td>
  <p class="date"><%= schedule.created_at.strftime("%Y年%m月%d日(#{%w(日 月 火 水 木 金 土)[schedule.created_at.wday]})" ) %></p>
</td>

<td><% if schedule.in.present? %>
    <%= schedule.in.strftime('%H:%M') %>
    <% else %>
    <%="記録されていません" %>
    <% end %>
</td>

<td><% if schedule.out.present? %>
    <%= schedule.out.strftime('%H:%M') %>
    <%else%>
    <%= "記録されていません" %>
    <% end %>
</td>

<td>
<%= link_to "修正", "/users/#{schedule.user_id}/schedules/#{schedule.id}" %>
</td>

<td>
  <%= link_to "削除", "/users/#{schedule.user_id}/schedules/#{schedule.id}", method: :delete, type: "submit", class: 'input_btn', data:{ confirm: "削除しますか？", commit: "はい", cancel: "いいえ"} %>
</td>
</tr>
<% end %>
</table>
</div>


 <footer>
    <div class="setting_box">
      <a href="/users/new">
      <div class="setting_box__button" id="registration">
          <i class="fas fa-user-plus"></i><span class="setting_box__button-text">登録</span>
      </div>
      </a>
      <a href="/users/show">
      <div class="setting_box__button">
           <i class="fas fa-user-cog"></i><span class="setting_box__button-text">戻る</span>
      </div>
      </a>
    </div>
  </footer>

app/views/schedules/show.html.erb
<%= render partial: "users/header" %>

<div class="table__box">

<div class="upper_area">
<p class="employee_name">
<%= @user.name %> さんの<%= @schedule.created_at.strftime("%Y年%m月%d日(#{%w(日 月 火 水 木 金 土)[@schedule.created_at.wday]})" ) %> の退勤時間を修正
</p>
</div>

<%= form_for [@schedule], url: user_schedule_path do |f| %>
<table class="list_table__style">

<th>出勤</th>
<th>退勤</th>
<th class="change">修正</th>

<tr>
<td>
  <%= f.time_field :in, class: 'input_box' %>
</td>

<td>
  <%= f.time_field :out, class: 'input_box' %>
</td>

<td>
  <%= f.submit :修正, type: "submit", class: 'input_btn', data:{ confirm: "変更しますか？", commit: "はい", cancel: "いいえ"} do %>
</td>

</tr>
<% end %>
</table>
</div>





<footer>
    <div class="setting_box">
      <a href=" /users/<%= @schedule.user_id %>/schedules">
      <div class="setting_box__button" id="registration">
           <i class="fas fa-user-cog"></i><span class="setting_box__button-text">戻る</span>
      </div>
      </a>
      <a href="/">
      <div class="setting_box__button">
          <i class="fas fa-home"></i><span class="setting_box__button-text">TOP</span>
      </div>
      </a>
    </div>
  <% end %>
  </footer>

app/views/users/_employee.html.erb
<% if sch.present? %>
      <li class="employee__box__list__name", id="leave", data-user-id="<%=user.id%>"><%= user.name %></li>
      <% elsif user.schedules.ids.last.nil?%>
      <li class="employee__box__list__name", id="leave", data-user-id="<%=user.id%>"><%= user.name %></li>
      <% else %>
      <li class="employee__box__list__name_select", id="attend", data-user-id="<%=user.id%>"><%= user.name %></li>
<% end %>

app/views/users/_header.html.erb
<header>
  <a href="/"><h1 class="title">きんたいあぷり</h1></a><span class="header__realtime" id="datetime"></span>
</header>

app/views/users/_list.html.erb
<% @users.each do |user| %>
<div class="list_box">
  <p class="list_box__name">
    <%= user.name %>
  </p>

<div class="list_box__button">
<%= link_to "勤怠一覧", user_schedules_path(user), class:"list_box__button--text"  %>
</div>

<div class="list_box__button">
<%= link_to "変更", "/users/#{user.id}/edit", class:"list_box__button--text" %>
</div>


<div class="list_box__button">
<%= link_to "削除", "#{user.id}", method: :delete, class:"list_box__button--text", data:{ confirm: "削除しますか？", commit: "削除", cancel: "キャンセル"}, title: "ご確認ください"  %>
</div>
</div>
<% end %>

app/views/users/edit.html.erb
<%= render partial: "header" %>
<div class="form_box">
<h2>登録内容変更</h2>

<%= form_with(model: @user) do |f| %>
  <div class="form_box__category">
  <%= f.label :氏名, class:'label_text' %>
  <%= f.text_field :name, placeholder: '氏名を入れてください', class:'input_area' %>
  </div>
  <br>
  <div class="form_box__category">
  <%= f.label :メール, class:'label_text' %>
  <%= f.text_field :email, placeholder: 'メールアドレスを入れてください', class:'input_area' %>
  </div>
  <br>
  <div class="form_box__category">
  <%= f.label :パスワード, class:'label_text' %>
  <%= f.password_field :password, placeholder: 'パスワードを入れてください', class:'input_area' %>
  </div>
  <div class="form_box__category">
    <%= render 'layouts/flash' %>
  </div>
  <div class="form_box__category">
      <%= f.submit :変更, type: "submit", class:'form_button', data:{ confirm: "変更しますか？", commit: "はい", cancel: "いいえ"} do %>
    <% end %>
<% end %>
</div>
</div>

  <footer>
    <div class="setting_box">
      <a href="/users/new">
      <div class="setting_box__button" id="registration">
          <i class="fas fa-user-plus"></i><span class="setting_box__button-text">登録</span>
      </div>
      </a>
      <a href="/">
      <div class="setting_box__button">
          <i class="fas fa-home"></i><span class="setting_box__button-text">戻る</span>
      </div>
      </a>
    </div>
  </footer>

app/views/users/index.html.erb
<%= render partial: "header" %>
  <div class="employee__box">
  <% @users.zip(@sch).each do |user, sch| %>
  <ul class="employee__box__list">
  <%= render partial: "employee", locals: { user: user, sch: sch} %>
  </ul>
  <% end %>
  </div>
  <footer>
    <div class="setting_box">
      <a href="/users/show">
        <div class="setting_box__button">
        <i class="fas fa-user-cog"></i><span class="setting_box__button-text">設定</span>
      </div>
      </a>
      <a href="/users/new">
      <div class="setting_box__button" id="registration">
          <i class="fas fa-user-plus"></i><span class="setting_box__button-text">登録</span>
      </div>
      </a>
    </div>
  </footer>

app/views/users/new.html.erb
<%= render partial: "header" %>
<div class="form_box">
<h2>新規登録</h2>

<%= form_with model:@user do |f| %>
<div class="form_box__category">
<%= f.label :氏名, class:'label_text' %>
<%= f.text_field :name, placeholder: '氏名を入れてください', class:'input_area' %>
</div>
<br>
<div class="form_box__category">
<%= f.label :メール, class:'label_text' %>
<%= f.text_field :email, placeholder: 'メールアドレスを入れてください', class:'input_area' %>
</div>
<br>
<div class="form_box__category">
<%= f.label :パスワード, class:'label_text' %>
<%= f.password_field :password, placeholder: 'パスワードを入れてください', class:'input_area' %>
</div>
<div class="form_box__category">
<%= f.submit :登録, type: "submit", class:'form_button',data:{ confirm: "登録しますか？", commit: "はい", cancel: "いいえ"} do %>
<% end %>
<% end %>
</div>
</div>
  <footer>
    <div class="setting_box">
      <a href="/users/show">
        <div class="setting_box__button" id="setting">
        <i class="fas fa-user-cog"></i><span class="setting_box__button-text">設定</span>
      </div>
      </a>
      <a href="/">
      <div class="setting_box__button">
          <i class="fas fa-home"></i><span class="setting_box__button-text">戻る</span>
      </div>
      </a>
    </div>
  </footer>

app/views/users/show.html.erb
<%= render partial: "header" %>

<%= render partial: "list"%>

<footer>
    <div class="setting_box">
      <a href="/users/new">
      <div class="setting_box__button" id="registration">
          <i class="fas fa-user-plus"></i><span class="setting_box__button-text">登録</span>
      </div>
      </a>
      <a href="/">
      <div class="setting_box__button">
          <i class="fas fa-home"></i><span class="setting_box__button-text">戻る</span>
      </div>
      </a>
    </div>
  </footer>